[package]
name = "sqli"
version = "0.1.0"
authors = ["Jarrod Servilla <jarrod.servilla@gmail.com>"]
license = "GPL-3.0-or-later"
description = "A command line tool for interacting with SQL databases"
readme = "README.md"
homepage = "https://github.com/jcserv/sqli"
repository = "https://github.com/jcserv/sqli"
keywords = ["cli", "env", "config", "environment"]
categories = ["command-line-utilities", "development-tools"]
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
